### ISSUE TITLE
Add formula tree example

### ISSUE THREAD

**Issue by ridderl** [NLeSC/MAGMa#149]
Use the following line below the text area:

Examples:    Chlorogenic acid (Mass Tree)    Chlorogenic acid (Formula Tree)

"Examples" is text with hyperlink to "information on examples"
"Chlorogenic acid (Mass Tree)" is a button
"Chlorogenic acid (Formula Tree)" is a button

The formula tree is:

``` yaml
C16H17O9: 69989984 (
    C7H11O6: 54674544 (
        C4H5O2: 2596121,
        C6H5O: 1720164,
        C6H5O2: 917026,
        C6H7O2: 1104891 (
            C5H5O: 28070,
            C4H3O2: 7618,
            C5H7O: 25471,
            C6H5O: 36300,
            C5H4O2: 8453
            ),
        C6H7O3: 2890439 (
            C3H5O: 16911,
            C5H5O: 41459,
            C5H7O: 35131,
            C4H5O2: 236887,
            C5H7O2: 73742,
            C6H5O2: 78094
            ),
        C7H7O5: 905226,
        C7H9O5: 2285841 (
            C3H3O2: 27805,
            C6H5O: 393710,
            C5H3O3: 26219,
            C6H7O2: 339595,
            C7H5O3: 27668,
            C7H7O4: 145773
            ),
        C7H11O6: 17000514
        ),
    C16H17O9: 4146696
    )



```
